In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
metamag = pd.read_csv('../CentralDogma/5_Wrath_/bd120_crossed.csv')

metamag.loc[metamag['dist']<0.1][['ID', 'lp_type']]

       ID  lp_type
3    2304        0
15   2316        0
21   2319        0
27   2322        0
31  12003        0

In [4]:
metamag.loc[(metamag['dist']<1.5)&(metamag['dist']>1)][['ID', 'lp_type', 'dist', 'cntr_01', 'ra_01', 'dec_01']]

       ID  lp_type      dist  cntr_01       ra_01    dec_01
5    2405        0  1.130257        5  150.187686  2.102767
13   2314        0  1.359805       13  149.877578  2.077665
41  12053        0  1.229684       32  149.923737  1.978152
44  12070        0  1.163713       34  149.898406  2.212485

In [5]:
for column in metamag.columns[25:33]:
    print(f' {column} : {metamag.loc[metamag["ID"]==12026][column].values[0]}')

 uvista_y_mag_auto : 25.4341
 uvista_y_magerr_auto : 0.1533
 uvista_j_mag_auto : 25.1467
 uvista_j_magerr_auto : 0.1384
 uvista_h_mag_auto : 25.6014
 uvista_h_magerr_auto : 0.2884
 uvista_ks_mag_auto : 26.0314
 uvista_ks_magerr_auto : 0.2884

In [32]:
for column in metamag.columns[-35:-11]:
    print(f' {column} : {metamag.loc[metamag["ID"]==2304][column].values[0]}')
# metamag.loc[metamag['ID']==2318]

 acs_f814w_magerr : 0.2307
 lp_type : 0
 lp_zpdf : 7.1875
 lp_zpdf_l68 : 7.1362
 lp_zpdf_u68 : 7.2384
 lp_nbfilt : 33
 lp_age : 230000000.0
 lp_dust : 0.0
 lp_attenuation : 0
 lp_mfuv : -23.7715
 lp_mnuv : -23.4096
 lp_mu : -22.9188
 lp_mg : -23.0504
 lp_mr : -23.7616
 lp_mi : -23.5291
 lp_mz : -23.5373
 lp_my : -23.5266
 lp_mj : -23.4565
 lp_mh : -23.4289
 lp_mk : -23.0962
 lp_mass_med : 9.841
 lp_sfr_med : 1.855
 lp_ssfr_med : -7.995
 ez_z160 : 7.1278